version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx.nginx
    environment:
      APP_PATH: /app
      PORT: 3000
    ports:
      - "80:80"
    # volumes:
    #   - ./web:/app
    depends_on:
      - web
  bundle_cache:
    image: busybox
    volumes:
      - bundle_cache:/bundle
  db:
    image: postgres
    container_name: db.postgres
    environment:
      POSTGRES_PASSWORD: password
    ports: 
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data  
  web:
    build: 
      context: ./web
    container_name: web.rails
    environment:
      APP_PATH: /app
      BUNDLE_PATH: /bundle
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
      PORT: 3000
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b "0.0.0.0"
    volumes:
      - ./web:/app
      - bundle_cache:/bundle
    depends_on:
      - bundle_cache
      - db
volumes:
  bundle_cache:
